/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author pzapata
 */
public class TelaSelecao extends javax.swing.JFrame {

    /**
     * Creates new form TelaSelecao
     */
    public TelaSelecao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpAlternativas = new javax.swing.ButtonGroup();
        rdBtnA = new javax.swing.JRadioButton();
        rdBtnB = new javax.swing.JRadioButton();
        rdBtnC = new javax.swing.JRadioButton();
        rdBtnD = new javax.swing.JRadioButton();
        rdBtnE = new javax.swing.JRadioButton();
        lblSelec = new javax.swing.JLabel();
        btnTranscr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGrpAlternativas.add(rdBtnA);
        rdBtnA.setSelected(true);
        rdBtnA.setText("The quick");

        btnGrpAlternativas.add(rdBtnB);
        rdBtnB.setText("brown fox");

        btnGrpAlternativas.add(rdBtnC);
        rdBtnC.setText("jumps over");

        btnGrpAlternativas.add(rdBtnD);
        rdBtnD.setText("the lazy");

        btnGrpAlternativas.add(rdBtnE);
        rdBtnE.setText("dog.");
        rdBtnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnEActionPerformed(evt);
            }
        });

        lblSelec.setText("Valor da seleção");

        btnTranscr.setText("Transcreve");
        btnTranscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtnA)
                            .addComponent(rdBtnB)
                            .addComponent(rdBtnC)
                            .addComponent(rdBtnD)
                            .addComponent(btnTranscr)
                            .addComponent(rdBtnE))
                        .addGap(0, 293, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(rdBtnA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBtnB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBtnC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBtnD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBtnE)
                .addGap(33, 33, 33)
                .addComponent(btnTranscr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lblSelec)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdBtnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnEActionPerformed

    private void btnTranscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscrActionPerformed
        // TODO add your handling code here:
        if (rdBtnA.isSelected()) lblSelec.setText(rdBtnA.getText());
        if (rdBtnB.isSelected()) lblSelec.setText(rdBtnB.getText());
        if (rdBtnC.isSelected()) lblSelec.setText(rdBtnC.getText());
        if (rdBtnD.isSelected()) lblSelec.setText(rdBtnD.getText());
        if (rdBtnE.isSelected()) lblSelec.setText(rdBtnE.getText());
    }//GEN-LAST:event_btnTranscrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSelecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpAlternativas;
    private javax.swing.JButton btnTranscr;
    private javax.swing.JLabel lblSelec;
    private javax.swing.JRadioButton rdBtnA;
    private javax.swing.JRadioButton rdBtnB;
    private javax.swing.JRadioButton rdBtnC;
    private javax.swing.JRadioButton rdBtnD;
    private javax.swing.JRadioButton rdBtnE;
    // End of variables declaration//GEN-END:variables
}
